name: sistema_restaurante
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  postgres: ^3.0.3
  provider: ^6.1.1
  web_socket_channel: ^2.4.0
  dart_frog_web_socket: ^1.0.0
  dart_frog_cli: ^1.2.0
  socket_io_client: ^2.0.3+1
  shelf_web_socket: ^1.0.4
  shelf: ^1.4.1
  intl: ^0.19.0
  universal_html: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - images/
