name: sistema_restaurante
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0
  flutter_email_sender: ^5.0.2
  path_provider: ^2.0.8
  advance_pdf_viewer: ^2.0.0
  open_file: ^3.3.2
  pdf: ^3.10.7
  flutter_paypal_payment: ^1.0.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  postgres: ^3.0.3
  provider: ^6.1.1
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  shelf_web_socket: ^1.0.4
  shelf: ^1.4.1
  intl: ^0.19.0
  universal_html: ^2.0.14
  soundpool: ^2.3.0
  responsive_builder: ^0.7.0
  fl_chart: ^0.66.0
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - images/
    - assets/Audio/
